/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	demov1 "knative.dev/sample-controller/pkg/apis/demo/v1"
)

// FakeMyDeployments implements MyDeploymentInterface
type FakeMyDeployments struct {
	Fake *FakeSamplesV1
	ns   string
}

var mydeploymentsResource = schema.GroupVersionResource{Group: "samples.knative.dev", Version: "v1", Resource: "mydeployments"}

var mydeploymentsKind = schema.GroupVersionKind{Group: "samples.knative.dev", Version: "v1", Kind: "MyDeployment"}

// Get takes name of the myDeployment, and returns the corresponding myDeployment object, and an error if there is any.
func (c *FakeMyDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *demov1.MyDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mydeploymentsResource, c.ns, name), &demov1.MyDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.MyDeployment), err
}

// List takes label and field selectors, and returns the list of MyDeployments that match those selectors.
func (c *FakeMyDeployments) List(ctx context.Context, opts v1.ListOptions) (result *demov1.MyDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mydeploymentsResource, mydeploymentsKind, c.ns, opts), &demov1.MyDeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &demov1.MyDeploymentList{ListMeta: obj.(*demov1.MyDeploymentList).ListMeta}
	for _, item := range obj.(*demov1.MyDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested myDeployments.
func (c *FakeMyDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mydeploymentsResource, c.ns, opts))

}

// Create takes the representation of a myDeployment and creates it.  Returns the server's representation of the myDeployment, and an error, if there is any.
func (c *FakeMyDeployments) Create(ctx context.Context, myDeployment *demov1.MyDeployment, opts v1.CreateOptions) (result *demov1.MyDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mydeploymentsResource, c.ns, myDeployment), &demov1.MyDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.MyDeployment), err
}

// Update takes the representation of a myDeployment and updates it. Returns the server's representation of the myDeployment, and an error, if there is any.
func (c *FakeMyDeployments) Update(ctx context.Context, myDeployment *demov1.MyDeployment, opts v1.UpdateOptions) (result *demov1.MyDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mydeploymentsResource, c.ns, myDeployment), &demov1.MyDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.MyDeployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMyDeployments) UpdateStatus(ctx context.Context, myDeployment *demov1.MyDeployment, opts v1.UpdateOptions) (*demov1.MyDeployment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mydeploymentsResource, "status", c.ns, myDeployment), &demov1.MyDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.MyDeployment), err
}

// Delete takes name of the myDeployment and deletes it. Returns an error if one occurs.
func (c *FakeMyDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mydeploymentsResource, c.ns, name), &demov1.MyDeployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMyDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mydeploymentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &demov1.MyDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched myDeployment.
func (c *FakeMyDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *demov1.MyDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mydeploymentsResource, c.ns, name, pt, data, subresources...), &demov1.MyDeployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*demov1.MyDeployment), err
}
