/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "knative.dev/sample-controller/pkg/apis/demo/v1"
	scheme "knative.dev/sample-controller/pkg/client/clientset/versioned/scheme"
)

// MyDeploymentsGetter has a method to return a MyDeploymentInterface.
// A group's client should implement this interface.
type MyDeploymentsGetter interface {
	MyDeployments(namespace string) MyDeploymentInterface
}

// MyDeploymentInterface has methods to work with MyDeployment resources.
type MyDeploymentInterface interface {
	Create(ctx context.Context, myDeployment *v1.MyDeployment, opts metav1.CreateOptions) (*v1.MyDeployment, error)
	Update(ctx context.Context, myDeployment *v1.MyDeployment, opts metav1.UpdateOptions) (*v1.MyDeployment, error)
	UpdateStatus(ctx context.Context, myDeployment *v1.MyDeployment, opts metav1.UpdateOptions) (*v1.MyDeployment, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MyDeployment, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MyDeploymentList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MyDeployment, err error)
	MyDeploymentExpansion
}

// myDeployments implements MyDeploymentInterface
type myDeployments struct {
	client rest.Interface
	ns     string
}

// newMyDeployments returns a MyDeployments
func newMyDeployments(c *SamplesV1Client, namespace string) *myDeployments {
	return &myDeployments{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the myDeployment, and returns the corresponding myDeployment object, and an error if there is any.
func (c *myDeployments) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MyDeployment, err error) {
	result = &v1.MyDeployment{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mydeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MyDeployments that match those selectors.
func (c *myDeployments) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MyDeploymentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MyDeploymentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mydeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested myDeployments.
func (c *myDeployments) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mydeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a myDeployment and creates it.  Returns the server's representation of the myDeployment, and an error, if there is any.
func (c *myDeployments) Create(ctx context.Context, myDeployment *v1.MyDeployment, opts metav1.CreateOptions) (result *v1.MyDeployment, err error) {
	result = &v1.MyDeployment{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mydeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myDeployment).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a myDeployment and updates it. Returns the server's representation of the myDeployment, and an error, if there is any.
func (c *myDeployments) Update(ctx context.Context, myDeployment *v1.MyDeployment, opts metav1.UpdateOptions) (result *v1.MyDeployment, err error) {
	result = &v1.MyDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mydeployments").
		Name(myDeployment.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myDeployment).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *myDeployments) UpdateStatus(ctx context.Context, myDeployment *v1.MyDeployment, opts metav1.UpdateOptions) (result *v1.MyDeployment, err error) {
	result = &v1.MyDeployment{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mydeployments").
		Name(myDeployment.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myDeployment).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the myDeployment and deletes it. Returns an error if one occurs.
func (c *myDeployments) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mydeployments").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *myDeployments) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mydeployments").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched myDeployment.
func (c *myDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MyDeployment, err error) {
	result = &v1.MyDeployment{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mydeployments").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
