/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	demov1 "knative.dev/sample-controller/pkg/apis/demo/v1"
	versioned "knative.dev/sample-controller/pkg/client/clientset/versioned"
	internalinterfaces "knative.dev/sample-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "knative.dev/sample-controller/pkg/client/listers/demo/v1"
)

// MyDeploymentInformer provides access to a shared informer and lister for
// MyDeployments.
type MyDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MyDeploymentLister
}

type myDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMyDeploymentInformer constructs a new informer for MyDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMyDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMyDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMyDeploymentInformer constructs a new informer for MyDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMyDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplesV1().MyDeployments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SamplesV1().MyDeployments(namespace).Watch(context.TODO(), options)
			},
		},
		&demov1.MyDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *myDeploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMyDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&demov1.MyDeployment{}, f.defaultInformer)
}

func (f *myDeploymentInformer) Lister() v1.MyDeploymentLister {
	return v1.NewMyDeploymentLister(f.Informer().GetIndexer())
}
