apiVersion: v1
kind: Pod
metadata:
  name: helloworld-java
  namespace: paas-yewu
spec:
  containers:
    - name: web
      image: boatswain.registry.si-tech.com.cn:30100/paas-yewu/helloworld-java
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP